services:
  - type: web
    name: ghostshell-mmo
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PORT
        value: 10000
      - key: ENV
        value: production
      - key: HOST
        value: wss://ghostshell.onrender.com
      - key: SECRET_KEY
        value: abc123
